### ISSUE TITLE
Error creating user

### ISSUE THREAD

**Issue by baardl** [Cantara/Whydah-UserIdentityBackend#17]
User:
String username = "_temp_username_" + System.currentTimeMillis();
        UserIdentityRepresentation userIdentity = new UserIdentityRepresentation(username,"first","last","ref",username +"@example.com","+4712345678");

Error:
5:47:02.457 [Grizzly(5)] TRACE n.w.i.user.resource.UserResource - addUserIdentity, userIdentityJson={"username":"_temp_username_1434635221960","firstName":"first","lastName":"last","personRef":"ref","email":"_temp_username_1434635221960@example.com","cellPhone":"null"}
15:47:02.469 [Grizzly(5)] TRACE n.w.i.u.identity.LdapUserIdentityDao - getUserAttributesForUsername using initials=_temp_username_1434635221960
15:47:02.477 [Grizzly(5)] TRACE n.w.i.u.identity.LdapUserIdentityDao - No attributes found for username. Search on: initials=_temp_username_1434635221960
15:47:02.477 [Grizzly(5)] DEBUG n.w.i.u.identity.LdapUserIdentityDao - No attributes found for username=_temp_username_1434635221960, trying uid
15:47:02.477 [Grizzly(5)] DEBUG n.w.i.u.identity.LdapUserIdentityDao - getAttributesForUid, uid=_temp_username_1434635221960
15:47:02.477 [Grizzly(5)] TRACE n.w.i.u.identity.LdapUserIdentityDao - getAttributesForUid using uid=_temp_username_1434635221960
15:47:02.479 [Grizzly(5)] TRACE n.w.i.u.identity.LdapUserIdentityDao - No attributes found for uid. Search on: uid=_temp_username_1434635221960
15:47:02.480 [Grizzly(5)] DEBUG n.w.i.user.search.LuceneSearch - Original query=_temp_username_1434635221960@example.com, wildcard query= ^2 * temp^2 temp* username^2 username* 1434635221960@example.com^2 1434635221960@example.com* 
15:47:02.484 [Grizzly(5)] ERROR n.w.i.user.search.LuceneSearch - Could not parse wildCardQuery=^2 * temp^2 temp* username^2 username* 1434635221960@example.com^2 1434635221960@example.com* . Returning empty search result.
org.apache.lucene.queryparser.classic.ParseException: Cannot parse '^2 * temp^2 temp* username^2 username* 1434635221960@example.com^2 1434635221960@example.com* ': Encountered " "^" "^ "" at line 1, column 0.
Was expecting one of:
    <NOT> ...
    "+" ...
    "-" ...
    <BAREOPER> ...
    "(" ...
    "*" ...
    <QUOTED> ...
    <TERM> ...
    <PREFIXTERM> ...
    <WILDTERM> ...
    <REGEXPTERM> ...
    "[" ...
    "{" ...
    <NUMBER> ...
    <TERM> ...
    "*" ...
    
	at org.apache.lucene.queryparser.classic.QueryParserBase.parse(QueryParserBase.java:132) ~[lucene-queryparser-4.10.4.jar:4.10.4 1662817 - mike - 2015-02-27 16:39:11]
	at net.whydah.identity.user.search.LuceneSearch.search(LuceneSearch.java:53) ~[classes/:na]
	at net.whydah.identity.user.identity.UserIdentityService.addUserIdentityWithGeneratedPassword(UserIdentityService.java:147) [classes/:na]
	at net.whydah.identity.user.resource.UserResource.addUserIdentity(UserResource.java:78) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45-internal]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_45-internal]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45-internal]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45-internal]
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:187) [jersey-server-1.6.jar:1.6]
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:71) [jersey-server-1.6.jar:1.6]
	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:280) [jersey-server-1.6.jar:1.6]
	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108) [jersey-server-1.6.jar:1.6]
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) [jersey-server-1.6.jar:1.6]
	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84) [jersey-server-1.6.jar:1.6]
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1341) [jersey-server-1.6.jar:1.6]
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1273) [jersey-server-1.6.jar:1.6]
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1223) [jersey-server-1.6.jar:1.6]
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1213) [jersey-server-1.6.jar:1.6]
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:414) [jersey-server-1.6.jar:1.6]
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:537) [jersey-server-1.6.jar:1.6]
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:699) [jersey-server-1.6.jar:1.6]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:847) [javax.servlet-3.0.jar:na]
	at org.glassfish.grizzly.servlet.ServletHandler$FilterChainImpl.doFilter(ServletHandler.java:987) [grizzly-http-servlet-2.1.11.jar:2.1.11]
	at net.whydah.identity.security.SecurityFilter.doFilter(SecurityFilter.java:113) [classes/:na]
	at org.glassfish.grizzly.servlet.ServletHandler$FilterChainImpl.doFilter(ServletHandler.java:971) [grizzly-http-servlet-2.1.11.jar:2.1.11]
	at com.google.inject.servlet.DefaultFilterPipeline.dispatch(DefaultFilterPipeline.java:43) [guice-servlet-3.0.jar:na]
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113) [guice-servlet-3.0.jar:na]
	at org.glassfish.grizzly.servlet.ServletHandler$FilterChainImpl.doFilter(ServletHandler.java:971) [grizzly-http-servlet-2.1.11.jar:2.1.11]
	at org.glassfish.grizzly.servlet.ServletHandler$FilterChainImpl.invokeFilterChain(ServletHandler.java:930) [grizzly-http-servlet-2.1.11.jar:2.1.11]
	at org.glassfish.grizzly.servlet.ServletHandler.doServletService(ServletHandler.java:382) [grizzly-http-servlet-2.1.11.jar:2.1.11]
	at org.glassfish.grizzly.servlet.ServletHandler.service(ServletHandler.java:330) [grizzly-http-servlet-2.1.11.jar:2.1.11]
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:163) [grizzly-http-server-2.1.11.jar:2.1.11]
	at org.glassfish.grizzly.http.server.HttpHandlerChain.service(HttpHandlerChain.java:207) [grizzly-http-server-2.1.11.jar:2.1.11]
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:163) [grizzly-http-server-2.1.11.jar:2.1.11]
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:161) [grizzly-http-server-2.1.11.jar:2.1.11]
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119) [grizzly-framework-2.1.11.jar:2.1.11]
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284) [grizzly-framework-2.1.11.jar:2.1.11]
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:219) [grizzly-framework-2.1.11.jar:2.1.11]
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:149) [grizzly-framework-2.1.11.jar:2.1.11]
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:127) [grizzly-framework-2.1.11.jar:2.1.11]
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:78) [grizzly-framework-2.1.11.jar:2.1.11]
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:835) [grizzly-framework-2.1.11.jar:2.1.11]
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:103) [grizzly-framework-2.1.11.jar:2.1.11]
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:111) [grizzly-framework-2.1.11.jar:2.1.11]
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:55) [grizzly-framework-2.1.11.jar:2.1.11]
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:131) [grizzly-framework-2.1.11.jar:2.1.11]
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:572) [grizzly-framework-2.1.11.jar:2.1.11]
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:552) [grizzly-framework-2.1.11.jar:2.1.11]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45-internal]
Caused by: org.apache.lucene.queryparser.classic.ParseException: Encountered " "^" "^ "" at line 1, column 0.
Was expecting one of:
    <NOT> ...
    "+" ...
    "-" ...
    <BAREOPER> ...
    "(" ...
    "*" ...
    <QUOTED> ...
    <TERM> ...
    <PREFIXTERM> ...
    <WILDTERM> ...
    <REGEXPTERM> ...
    "[" ...
    "{" ...
    <NUMBER> ...
    <TERM> ...
    "*" ...
    
	at org.apache.lucene.queryparser.classic.QueryParser.generateParseException(QueryParser.java:710) ~[lucene-queryparser-4.10.4.jar:4.10.4 1662817 - mike - 2015-02-27 16:39:11]
	at org.apache.lucene.queryparser.classic.QueryParser.jj_consume_token(QueryParser.java:592) ~[lucene-queryparser-4.10.4.jar:4.10.4 1662817 - mike - 2015-02-27 16:39:11]
	at org.apache.lucene.queryparser.classic.QueryParser.Clause(QueryParser.java:277) ~[lucene-queryparser-4.10.4.jar:4.10.4 1662817 - mike - 2015-02-27 16:39:11]
	at org.apache.lucene.queryparser.classic.QueryParser.Query(QueryParser.java:183) ~[lucene-queryparser-4.10.4.jar:4.10.4 1662817 - mike - 2015-02-27 16:39:11]
	at org.apache.lucene.queryparser.classic.QueryParser.TopLevelQuery(QueryParser.java:172) ~[lucene-queryparser-4.10.4.jar:4.10.4 1662817 - mike - 2015-02-27 16:39:11]
	at org.apache.lucene.queryparser.classic.QueryParserBase.parse(QueryParserBase.java:127) ~[lucene-queryparser-4.10.4.jar:4.10.4 1662817 - mike - 2015-02-27 16:39:11]
	... 48 common frames omitted
15:47:02.485 [Grizzly(5)] INFO  n.w.i.user.resource.UserResource - addUserIdentity returned Bad Request because Invalid cellPhone : null

**Comment by baardl** [comment]
Assigned to Totto due to weird Lucene output.....

**Comment by totto** [comment]
This is probably fixed in @sherriff branch, suggest we wait for merge

**Comment by baardl** [comment]
Waiting for retest.

**Comment by baardl** [comment]
For now:
- cellPhone must exist
- email must be uniqe

**Comment by sherriff** [comment]
The underscore character is a special character used in buildWildCardQuery. Need to decide if underscore is allowed or how to handle this...
