### ISSUE TITLE
SQLSyntaxErrorException when getApplications is called 

### ISSUE THREAD

**Issue by sherriff** [Cantara/Whydah-UserIdentityBackend#20]
12:34:06.680 [qtp446073433-27] TRACE n.w.i.a.ApplicationsResource - getApplications is called 
12:34:06.682 [qtp446073433-27] ERROR n.w.i.a.ApplicationsResource - 
org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [SELECT Id, Name, Secret, AvailableOrgNames, DefaultRoleName, DefaultOrgName from Application WHERE id=?]; nested exception is java.sql.SQLSyntaxErrorException: parameter marker not allowed
	at org.springframework.jdbc.support.SQLExceptionSubclassTranslator.doTranslate(SQLExceptionSubclassTranslator.java:91) ~[UserIdentityBackend-2.1-20150601.132158-10.jar:na]
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73) ~[UserIdentityBackend-2.1-20150601.132158-10.jar:na]
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81) ~[UserIdentityBackend-2.1-20150601.132158-10.jar:na]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:416) ~[UserIdentityBackend-2.1-20150601.132158-10.jar:na]
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:471) ~[UserIdentityBackend-2.1-20150601.132158-10.jar:na]
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:481) ~[UserIdentityBackend-2.1-20150601.132158-10.jar:na]
	at net.whydah.identity.application.ApplicationDao.getApplications(ApplicationDao.java:60) ~[UserIdentityBackend-2.1-20150601.132158-10.jar:na]
	at net.whydah.identity.application.ApplicationService.getApplications(ApplicationService.java:53) ~[UserIdentityBackend-2.1-20150601.132158-10.jar:na]
	at net.whydah.identity.application.ApplicationsResource.getApplications(ApplicationsResource.java:50) ~[UserIdentityBackend-2.1-20150601.132158-10.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_25]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) [UserIdentityBackend-2.1-20150601.132158-10.jar:na]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:164) [UserIdentityBackend-2.1-20150601.132158-10.jar:na]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:181) [UserIdentityBackend-2.1-20150601.132158-10.jar:na]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:158) [UserIdentityBackend-2.1-20150601.132158-10.jar:na]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:101) [UserIdentityBackend-2.1-20150601.132158-10.jar:na]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) [UserIdentityBackend-2.1-20150601.132158-10.jar:na]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) [UserIdentityBackend-2.1-20150601.132158-10.jar:na]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) [UserIdentityBackend-2.1-20150601.132158-10.jar:na]
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:305) [UserIdentityBackend-2.1-20150601.132158-10.jar:na]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [UserIdentityBackend-2.1-20150601.132158-10.jar:na]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [UserIdentityBackend-2.1-20150601.132158-10.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [UserIdentityBackend-2.1-20150601.132158-10.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [UserIdentityBackend-2.1-20150601.132158-10.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [UserIdentityBackend-2.1-20150601.132158-10.jar:na]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [UserIdentityBackend-2.1-20150601.132158-10.jar:na]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:288) [UserIdentityBackend-2.1-20150601.132158-10.jar:na]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1110) [UserIdentityBackend-2.1-20150601.132158-10.jar:na]
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:401) [UserIdentityBackend-2.1-20150601.132158-10.jar:na]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:386) [UserIdentityBackend-2.1-20150601.132158-10.jar:na]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:335) [UserIdentityBackend-2.1-20150601.132158-10.jar:na]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:222) [UserIdentityBackend-2.1-20150601.132158-10.jar:na]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:769) [UserIdentityBackend-2.1-20150601.132158-10.jar:na]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1667) [UserIdentityBackend-2.1-20150601.132158-10.jar:na]
	at net.whydah.identity.security.SecurityFilter.doFilter(SecurityFilter.java:148) [UserIdentityBackend-2.1-20150601.132158-10.jar:na]
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:344) [UserIdentityBackend-2.1-20150601.132158-10.jar:na]
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:261) [UserIdentityBackend-2.1-20150601.132158-10.jar:na]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650) [UserIdentityBackend-2.1-20150601.132158-10.jar:na]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583) [UserIdentityBackend-2.1-20150601.132158-10.jar:na]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [UserIdentityBackend-2.1-20150601.132158-10.jar:na]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577) [UserIdentityBackend-2.1-20150601.132158-10.jar:na]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223) [UserIdentityBackend-2.1-20150601.132158-10.jar:na]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125) [UserIdentityBackend-2.1-20150601.132158-10.jar:na]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) [UserIdentityBackend-2.1-20150601.132158-10.jar:na]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [UserIdentityBackend-2.1-20150601.132158-10.jar:na]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059) [UserIdentityBackend-2.1-20150601.132158-10.jar:na]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [UserIdentityBackend-2.1-20150601.132158-10.jar:na]
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52) [UserIdentityBackend-2.1-20150601.132158-10.jar:na]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [UserIdentityBackend-2.1-20150601.132158-10.jar:na]
	at org.eclipse.jetty.server.Server.handle(Server.java:485) [UserIdentityBackend-2.1-20150601.132158-10.jar:na]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:290) [UserIdentityBackend-2.1-20150601.132158-10.jar:na]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248) [UserIdentityBackend-2.1-20150601.132158-10.jar:na]
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [UserIdentityBackend-2.1-20150601.132158-10.jar:na]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:606) [UserIdentityBackend-2.1-20150601.132158-10.jar:na]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:535) [UserIdentityBackend-2.1-20150601.132158-10.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_25]
Caused by: java.sql.SQLSyntaxErrorException: parameter marker not allowed
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[UserIdentityBackend-2.1-20150601.132158-10.jar:na]
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[UserIdentityBackend-2.1-20150601.132158-10.jar:na]
	at org.hsqldb.jdbc.JDBCStatement.fetchResult(Unknown Source) ~[UserIdentityBackend-2.1-20150601.132158-10.jar:na]
	at org.hsqldb.jdbc.JDBCStatement.executeQuery(Unknown Source) ~[UserIdentityBackend-2.1-20150601.132158-10.jar:na]
	at org.apache.commons.dbcp.DelegatingStatement.executeQuery(DelegatingStatement.java:208) ~[UserIdentityBackend-2.1-20150601.132158-10.jar:na]
	at org.apache.commons.dbcp.DelegatingStatement.executeQuery(DelegatingStatement.java:208) ~[UserIdentityBackend-2.1-20150601.132158-10.jar:na]
	at org.springframework.jdbc.core.JdbcTemplate$1QueryStatementCallback.doInStatement(JdbcTemplate.java:455) ~[UserIdentityBackend-2.1-20150601.132158-10.jar:na]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:405) ~[UserIdentityBackend-2.1-20150601.132158-10.jar:na]
	... 54 common frames omitted
Caused by: org.hsqldb.HsqlException: parameter marker not allowed
	at org.hsqldb.error.Error.error(Unknown Source) ~[UserIdentityBackend-2.1-20150601.132158-10.jar:na]
	at org.hsqldb.error.Error.error(Unknown Source) ~[UserIdentityBackend-2.1-20150601.132158-10.jar:na]
	at org.hsqldb.ParserCommand.compileStatements(Unknown Source) ~[UserIdentityBackend-2.1-20150601.132158-10.jar:na]
	at org.hsqldb.Session.executeDirectStatement(Unknown Source) ~[UserIdentityBackend-2.1-20150601.132158-10.jar:na]
	at org.hsqldb.Session.execute(Unknown Source) ~[UserIdentityBackend-2.1-20150601.132158-10.jar:na]
	... 60 common frames omitted

**Comment by sherriff** [comment]
Note that the error is from an old jar file: UserIdentityBackend-2.1-20150601. Unable to duplicate error now. Reopen if error resurfaces.
