### ISSUE TITLE
Observed a few examples where the WhydahUserAdmin password gets broken

### ISSUE THREAD

**Issue by totto** [Cantara/Whydah-UserIdentityBackend#56]
We do not know how or why, but we should investigate and possibly add some guards/logging as the consequences are usually high

**Comment by totto** [comment]
By adding admin-user to help, we see that continous logins give this stacktrace

17:36:00.272 [qtp1061804750-27] TRACE n.w.i.u.a.UserAuthenticationEndpoint - UserAuthenticationCredentialDTOUserAuthenticationCredentialDTO{username='whydahadmin', facebookId='', netIQAccessToken=''} XML:org.glassfish.jersey.message.internal.EntityInputStream@38e7af2b
17:36:00.274 [qtp1061804750-27] ERROR n.w.i.u.identity.LdapAuthenticator - Error authenticating as superuser, check configuration
javax.naming.ServiceUnavailableException: ip-172-18-4-234.eu-west-1.compute.internal:389; socket closed
	at com.sun.jndi.ldap.Connection.readReply(Connection.java:454) ~[na:1.8.0_72]
	at com.sun.jndi.ldap.LdapClient.ldapBind(LdapClient.java:365) ~[na:1.8.0_72]
	at com.sun.jndi.ldap.LdapClient.authenticate(LdapClient.java:214) ~[na:1.8.0_72]
	at com.sun.jndi.ldap.LdapCtx.connect(LdapCtx.java:2788) ~[na:1.8.0_72]
	at com.sun.jndi.ldap.LdapCtx.<init>(LdapCtx.java:319) ~[na:1.8.0_72]
	at com.sun.jndi.ldap.LdapCtxFactory.getUsingURL(LdapCtxFactory.java:192) ~[na:1.8.0_72]
	at com.sun.jndi.ldap.LdapCtxFactory.getUsingURLs(LdapCtxFactory.java:210) ~[na:1.8.0_72]
	at com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxInstance(LdapCtxFactory.java:153) ~[na:1.8.0_72]
	at com.sun.jndi.ldap.LdapCtxFactory.getInitialContext(LdapCtxFactory.java:83) ~[na:1.8.0_72]
	at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:684) ~[na:1.8.0_72]
	at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:313) ~[na:1.8.0_72]
	at javax.naming.InitialContext.init(InitialContext.java:244) ~[na:1.8.0_72]
	at javax.naming.InitialContext.<init>(InitialContext.java:216) ~[na:1.8.0_72]
	at javax.naming.directory.InitialDirContext.<init>(InitialDirContext.java:101) ~[na:1.8.0_72]
	at net.whydah.identity.user.identity.LdapAuthenticator.findUserDN(LdapAuthenticator.java:125) [UserIdentityBackend-2.2-alpha-13-20160613.101141-1.jar:na]
	at net.whydah.identity.user.identity.LdapAuthenticator.authenticateUser(LdapAuthenticator.java:88) [UserIdentityBackend-2.2-alpha-13-20160613.101141-1.jar:na]
	at net.whydah.identity.user.identity.LdapAuthenticator.authenticate(LdapAuthenticator.java:57) [UserIdentityBackend-2.2-alpha-13-20160613.101141-1.jar:na]
	at net.whydah.identity.user.identity.UserIdentityService.authenticate(UserIdentityService.java:57) [UserIdentityBackend-2.2-alpha-13-20160613.101141-1.jar:na]
	at net.whydah.identity.user.authentication.UserAuthenticationEndpoint.authenticateUser(UserAuthenticationEndpoint.java:101) [UserIdentityBackend-2.2-alpha-13-20160613.101141-1.jar:na]
	at net.whydah.identity.user.authentication.UserAuthenticationEndpoint.authenticateUser(UserAuthenticationEndpoint.java:97) [UserIdentityBackend-2.2-alpha-13-20160613.101141-1.jar:na]
	at sun.reflect.GeneratedMethodAccessor77.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_72]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_72]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) [UserIdentityBackend-2.2-alpha-13-20160613.101141-1.jar:na]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) [UserIdentityBackend-2.2-alpha-13-20160613.101141-1.jar:na]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) [UserIdentityBackend-2.2-alpha-13-20160613.101141-1.jar:na]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160) [UserIdentityBackend-2.2-alpha-13-20160613.101141-1.jar:na]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) [UserIdentityBackend-2.2-alpha-13-20160613.101141-1.jar:na]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) [UserIdentityBackend-2.2-alpha-13-20160613.101141-1.jar:na]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) [UserIdentityBackend-2.2-alpha-13-20160613.101141-1.jar:na]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) [UserIdentityBackend-2.2-alpha-13-20160613.101141-1.jar:na]
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) [UserIdentityBackend-2.2-alpha-13-20160613.101141-1.jar:na]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [UserIdentityBackend-2.2-alpha-13-20160613.101141-1.jar:na]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [UserIdentityBackend-2.2-alpha-13-20160613.101141-1.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [UserIdentityBackend-2.2-alpha-13-20160613.101141-1.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [UserIdentityBackend-2.2-alpha-13-20160613.101141-1.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [UserIdentityBackend-2.2-alpha-13-20160613.101141-1.jar:na]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [UserIdentityBackend-2.2-alpha-13-20160613.101141-1.jar:na]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) [UserIdentityBackend-2.2-alpha-13-20160613.101141-1.jar:na]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) [UserIdentityBackend-2.2-alpha-13-20160613.101141-1.jar:na]
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:471) [UserIdentityBackend-2.2-alpha-13-20160613.101141-1.jar:na]
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:425) [UserIdentityBackend-2.2-alpha-13-20160613.101141-1.jar:na]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:383) [UserIdentityBackend-2.2-alpha-13-20160613.101141-1.jar:na]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:336) [UserIdentityBackend-2.2-alpha-13-20160613.101141-1.jar:na]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:223) [UserIdentityBackend-2.2-alpha-13-20160613.101141-1.jar:na]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:821) [UserIdentityBackend-2.2-alpha-13-20160613.101141-1.jar:na]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1685) [UserIdentityBackend-2.2-alpha-13-20160613.101141-1.jar:na]
	at net.whydah.identity.security.SecurityFilter.doFilter(SecurityFilter.java:209) [UserIdentityBackend-2.2-alpha-13-20160613.101141-1.jar:na]

**Comment by totto** [comment]
NB...   initial testing indicate this to be a problem with external OpenLDAP installations, and not the embedded apacheDS LDAP
