### ISSUE TITLE
resource leakage in UIB

### ISSUE THREAD

**Issue by totto** [Cantara/Whydah-UserIdentityBackend#58]
... 52 common frames omitted
Caused by: java.net.SocketException: Too many open files
	at java.net.Socket.createImpl(Socket.java:460)
	at java.net.Socket.<init>(Socket.java:431)
	at java.net.Socket.<init>(Socket.java:211)
	at com.sun.jndi.ldap.Connection.createSocket(Connection.java:363)
	at com.sun.jndi.ldap.Connection.<init>(Connection.java:203)
	... 70 common frames omitted
12:03:05.142 [hystrix-STSApplicationAuthGroup-7] DEBUG CommandValidateApplicationTokenId, pool: STSApplicationAuthGroup - CommandValidateApplicationTokenId, pool: STSApplicationAuthGroup - ok: {"result": "true"}
12:03:06.133 [qtp1447689627-36-acceptor-0@e6460ee-ServerConnector@a39f52{HTTP/1.1,[http/1.1]}{0.0.0.0:9995}] WARN  o.e.jetty.server.AbstractConnector - 
java.io.IOException: Too many open files
	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
	at org.eclipse.jetty.server.ServerConnector.accept(ServerConnector.java:355)
	at org.eclipse.jetty.server.AbstractConnector$Acceptor.run(AbstractConnector.java:595)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)
12:03:06.564 [hystrix-STSApplicationAuthGroup-7] DEBUG CommandValidateApplicationTokenId, pool: STSApplicationAuthGroup - CommandValidateApplicationTokenId, pool: STSApplicationAuthGroup - ok: {"result": "true"}
12:03:09.134 [qtp1447689627-36-acceptor-0@e6460ee-ServerConnector@a39f52{HTTP/1.1,[http/1.1]}{0.0.0.0:9995}] WARN  o.e.jetty.server.AbstractConnector - 
java.io.IOException: Too many open files
	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
	at org.eclipse.jetty.server.ServerConnector.accept(ServerConnector.java:355)
	at org.eclipse.jetty.server.AbstractConnector$Acceptor.run(AbstractConnector.java:595)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)
12:03:10.090 [hystrix-STSApplicationAuthGroup-7] DEBUG CommandValidateApplicationTokenId, pool: STSApplicationAuthGroup - CommandValidateApplicationTokenId, pool: STSApplicationAuthGroup - ok: {"result": "true"}
12:03:10.134 [qtp1447689627-36-acceptor-0@e6460ee-ServerConnector@a39f52{HTTP/1.1,[http/1.1]}{0.0.0.0:9995}] WARN  o.e.jetty.server.AbstractConnector - 
java.io.IOException: Too many open files
	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
	at org.eclipse.jetty.server.ServerConnector.accept(ServerConnector.java:355)
	at org.eclipse.jetty.server.AbstractConnector$Acceptor.run(AbstractConnector.java:595)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)
12:03:11.134 [qtp1447689627-36-acceptor-0@e6460ee-ServerConnector@a39f52{HTTP/1.1,[http/1.1]}{0.0.0.0:9995}] WARN  o.e.jetty.server.AbstractConnector - 
java.io.IOException: Too many open files
	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
	at org.eclipse.jetty.server.ServerConnector.accept(ServerConnector.java:355)
	at org.eclipse.jetty.server.AbstractConnector$Acceptor.run(AbstractConnector.java:595)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)
12:03:17.136 [qtp1447689627-36-acceptor-0@e6460ee-ServerConnector@a39f52{HTTP/1.1,[http/1.1]}{0.0.0.0:9995}] WARN  o.e.jetty.server.AbstractConnector - 
java.io.IOException: Too many open files
	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
	at org.eclipse.jetty.server.ServerConnector.accept(ServerConnector.java:355)
	at org.eclipse.jetty.server.AbstractConnector$Acceptor.run(AbstractConnector.java:595)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)
12:03:25.138 [qtp1447689627-36-acceptor-0@e6460ee-ServerConnector@a39f52{HTTP/1.1,[http/1.1]}{0.0.0.0:9995}] WARN  o.e.jetty.server.AbstractConnector - 
java.io.IOException: Too many open files
	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
	at org.eclipse.jetty.server.ServerConnector.accept(ServerConnector.java:355)
	at org.eclipse.jetty.server.AbstractConnector$Acceptor.run(AbstractConnector.java:595)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)
12:03:27.139 [qtp1447689627-36-acceptor-0@e6460ee-ServerConnector@a39f52{HTTP/1.1,[http/1.1]}{0.0.0.0:9995}] WARN  o.e.jetty.server.AbstractConnector - 
java.io.IOException: Too many open files
	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
	at org.eclipse.jetty.server.ServerConnector.accept(ServerConnector.java:355)
	at org.eclipse.jetty.server.AbstractConnector$Acceptor.run(AbstractConnector.java:595)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)
12:03:28.139 [qtp1447689627-36-acceptor-0@e6460ee-ServerConnector@a39f52{HTTP/1.1,[http/1.1]}{0.0.0.0:9995}] WARN  o.e.jetty.server.AbstractConnector - 
java.io.IOException: Too many open files
	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
	at org.eclipse.jetty.server.ServerConnector.accept(ServerConnector.java:355)
	at org.eclipse.jetty.server.AbstractConnector$Acceptor.run(AbstractConnector.java:595)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)
12:03:29.140 [qtp1447689627-36-acceptor-0@e6460ee-ServerConnector@a39f52{HTTP/1.1,[http/1.1]}{0.0.0.0:9995}] WARN  o.e.jetty.server.AbstractConnector - 
java.io.IOException: Too many open files
	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
	at org.eclipse.jetty.server.ServerConnector.accept(ServerConnector.java:355)
	at org.eclipse.jetty.server.AbstractConnector$Acceptor.run(AbstractConnector.java:595)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)
12:03:32.141 [qtp1447689627-36-acceptor-0@e6460ee-ServerConnector@a39f52{HTTP/1.1,[http/1.1]}{0.0.0.0:9995}] WARN  o.e.jetty.server.AbstractConnector - 
java.io.IOException: Too many open files
	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
	at org.eclipse.jetty.server.ServerConnector.accept(ServerConnector.java:355)
	at org.eclipse.jetty.server.AbstractConnector$Acceptor.run(AbstractConnector.java:595)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)

**Comment by totto** [comment]
interesting enough this works as a "built in" throttling in "DoS" traffic peaks... :)  works fine when reducing the load...

**Comment by totto** [comment]
The problem was too few filehandles (<4000) on the instrance
